from tkinter import*
import tkinter.messagebox as ms
root=Tk()
(h,w)=root.winfo_screenheight(),root.winfo_screenwidth()
root.geometry('%dx%d+0+0'%(w,h))
bus=PhotoImage (file=".\\Bus_for_project.png")
home=PhotoImage(file=".\\home.png")
Label(root,image=bus).grid(padx=w//3,pady=30,columnspan=20)
Label(root,text='Online Bus Booking System',bg='lightblue',fg='red',font='Arial 28 bold').grid(padx=w//3,pady=15,columnspan=20)
Label(root,text='Enter Journey Details',bg='lightgreen',fg='green',font='Arial 18 bold').grid(padx=w//3,columnspan=20)
To=Entry(root).grid(row=3,column=5)
Label(root,text='TO').grid(row=3,column=4)
From = Entry(root).grid(row=3,column=9)
Label(root,text='From').grid(row=3,column=8)
Date=Entry(root).grid(row=3,column=14)
Label(root,text='Journey date').grid(row=3,column=13)
Button(root,text='Show Bus').grid(row=3,column=15)
Button(root,image=home).grid(row=3,column=16)
Label(root,text='Select Bus',fg='green',font='Arial 12 bold').grid(row=4,column=5,pady=10)
Label(root,text='Operator',fg='green',font='Arial 12 bold').grid(row=4,column= 7,pady=10)
Label(root,text='BUS type',fg='green',font='Arial 12 bold').grid(row=4,column= 9,pady=10)
Label(root,text='Available/Capacity',fg='green',font='Arial 12 bold').grid(row=4,column= 11,pady=10)
Label(root,text='Fare',fg='green',font='Arial 12 bold').grid(row=4,column= 13,pady=10)
Bus_select = IntVar()
def bus_choice():
    Label(root,text='BUS'+str(int(Bus_select.get()))).grid(row=8,column=5)
    ms.showinfo("your choise",Bus_select.get())
Button(root,text='show choice',command=bus_choice).grid(row=9,column=5)
Radiobutton(root,text='BUS1',variable=Bus_select,value=1).grid(row=5,column=5)
Radiobutton(root,text='BUS2',variable=Bus_select,value=2).grid(row=6,column=5)
Radiobutton(root,text='BUS3',variable=Bus_select,value=3).grid(row=7,column=5)
